apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kqjgu2wxo-python 
  janus-idp.io/tekton: kqjgu2wxo-python
  backstage.io/kubernetes-id: kqjgu2wxo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kqjgu2wxo-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  