apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kqjgu2wxo-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kqjgu2wxo-python 
  name: kqjgu2wxo-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kqjgu2wxo-python 
